name: CI2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.303'

      - name: Restore dependencies
        run: dotnet restore TESTTEsT.sln

      - name: Build project
        run: dotnet build TESTTEsT.sln --configuration Release

      - name: Run tests
        run: dotnet test TESTTEsT.sln --configuration Release --no-build
